[package]
name = "rust-server"
version = "0.1.0"
authors = ["Alexander Weiss <alex@weissfam.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1", features = ["attributes"] }
async-trait = "0.1"
tide = "0.16"
tide-rustls = "0.2"
# local fix for tide-http-auth to support tide 0.16!
tide-http-auth = {path = "./tide-http-auth"}
http-range = "0.1"
serde = { version = "1", features = ["derive"] }
clap = "3.0.0-beta.2"
htpasswd-verify = "0.1"
toml = "0.5"
walkdir = "2"
