[package]
name = "rust-server"
version = "0.1.0"
authors = ["Alexander Weiss <alex@weissfam.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-std = { version = "1", features = ["attributes"] }
async-trait = "0.1"
clap = { version = "4.4.2", features = ["derive"] }
htpasswd-verify = "0.3"
http-range = "0.1"
serde = { version = "1", features = ["derive"] }
tide = "0.16"
# local fix for tide-http-auth to support tide 0.16!
tide-http-auth = "0.5"
tide-rustls = "0.3"
toml = "0.5"
walkdir = "2"
